### ISSUE TITLE
Design minor changes

### ISSUE THREAD

**Issue by inesiwadare** [BlickLabs/WorkingLab#3]
*Homepage*

- [x] Inicio, and both logos don't work (links)

- [x] Replace main image (pixelated) All the new images are in this folder: https://drive.google.com/drive/u/0/folders/0B28Mtq-TfWhWb2hLTTFRYklRZDg

- [x] Replace illustration (pixelated)

- [x] Add carrousel of images: number 1-3: https://drive.google.com/drive/u/0/folders/0B28Mtq-TfWhWb2hLTTFRYklRZDg

- [ ] Replace second image

- [x] All the buttons are in a different font
They are like this:
<img width="185" alt="screen shot 2017-04-04 at 7 24 18 am" src="https://cloud.githubusercontent.com/assets/17226545/24656335/bb840e1c-1907-11e7-8a3c-3d7500bcfa0e.png">

They should be like this:
<img width="195" alt="screen shot 2017-04-04 at 7 23 33 am" src="https://cloud.githubusercontent.com/assets/17226545/24656325/af14d508-1907-11e7-8f0e-45e4b15759d1.png">

- [x] Make the cover parallax 💃 

- [x] Can you make the second image a parallax too?

- [x] And the newsletter field? (parallax)
- [x] Replace the envelope icon (pixelated)
- [ ] Replace the image in the newsletter field
- [x] All the icons are pixelated 😢  The new ones are here: https://drive.google.com/drive/u/0/folders/0B28Mtq-TfWhWS0xiOEpOSDdUbnM

- [x] Same as last one:
<img width="100" alt="screen shot 2017-04-04 at 7 27 02 am" src="https://cloud.githubusercontent.com/assets/17226545/24656419/1f3656a4-1908-11e7-9a61-8572ff8e2ede.png">

*Precios*

- [x] Replace icons
*Nosotros*
- [ ] Replace image
<img width="1266" alt="screen shot 2017-04-04 at 7 27 43 am" src="https://cloud.githubusercontent.com/assets/17226545/24656456/43e1da96-1908-11e7-8139-c3fed54fea35.png">

*Contacto*
- [x] Buttons

*Partnership / Referidos*
- [x] Too much white space
<img width="1017" alt="screen shot 2017-04-04 at 7 29 08 am" src="https://cloud.githubusercontent.com/assets/17226545/24656498/71c382f2-1908-11e7-9233-00fc2974d9fe.png">

- [x] Notice anything different?
<img width="91" alt="screen shot 2017-04-04 at 7 28 53 am" src="https://cloud.githubusercontent.com/assets/17226545/24656511/780bd542-1908-11e7-90ff-c9d1ae9c27d4.png">

- [x] Replace icon
<img width="101" alt="screen shot 2017-04-04 at 7 29 05 am" src="https://cloud.githubusercontent.com/assets/17226545/24656515/7d1bf12a-1908-11e7-84f3-83ad58ae7859.png">

- [x] Link logo to homepage (error 404)
<img width="392" alt="screen shot 2017-04-04 at 7 30 09 am" src="https://cloud.githubusercontent.com/assets/17226545/24656534/956378e8-1908-11e7-9ab5-a331b1496d4f.png">

*Móvil*
***Es hermoso 😍

**Comment by AlanSanchezP** [comment]
@inesiwadare 
-Logo and "Inicio" links doesn't work but it's just in github pages, they work in the real domain
-Please send newsletter and blue buildings images in higher resolutions
-About us: I replaced the image but it looks the same
-I added dots in carousel but i couldn't make them smaller
